### ISSUE TITLE
Searchbox Error

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [VonHeikemen/searchbox.nvim#11]
**Command :**
- search `<leader>s` 
- replace `<leader>r`
- Close Searchbox `<esc> (escape)`  -> failed to close searchbox
- and maybe all.

This happen after nui.nvim [latest commit](https://github.com/MunifTanjim/nui.nvim/commit/c38056355f5a72c7a1a005f7125afd62ed7b2083)

https://user-images.githubusercontent.com/73665622/145864041-db5834e8-3c7d-4dcc-b5ee-e565750114ab.mp4

**Comment by VonHeikemen** [comment]
thanks for bringing this to my attention. It's fixed now in [1c551c0](https://github.com/VonHeikemen/searchbox.nvim/commit/1c551c0a6447cf13ada36574b4ee3a95c0ea117f).

**Comment by GreatestOfAllTimee** [comment]
> thanks for bringing this to my attention. It's fixed now in [1c551c0](https://github.com/VonHeikemen/searchbox.nvim/commit/1c551c0a6447cf13ada36574b4ee3a95c0ea117f).

Thank you!
