### ISSUE TITLE
clear_matches does not work

### ISSUE THREAD

**Issue by jrafaaael** [VonHeikemen/searchbox.nvim#12]
when I try this:
```lua
local map = vim.api.nvim_set_keymap
map('n', '<leader>S', ":SearchBoxMatchAll clear_matches=true<CR>", {noremap = true})
```
I search something in the searchbox and after press `enter`, the highlight words still appearing

**Comment by VonHeikemen** [comment]
do you have `hlsearch` enabled?

**Comment by jrafaaael** [comment]
@VonHeikemen is working now! Thank you for this plugin, I love it!
