### ISSUE TITLE
Cursor doesn't jump for out of focus search matches

### ISSUE THREAD

**Issue by zim0369** [VonHeikemen/searchbox.nvim#14]
If a cursor is say at the top and the search result is at the bottom(out of
screen's focus) then cursor doesn't jump to the search result until you press
return.

With the neovim's default `/` the cursor jumps to the search result.

**Comment by VonHeikemen** [comment]
can you tell me which type of search? `incsearch` works fine for me.

**Comment by zim0369** [comment]
> can you tell me which type of search? `incsearch` works fine for me.

Oh, It works fine but I didn't notice it because there's no highlighting. This
is my mapping:
```
map("n", "<C-f>", '<cmd>lua require("searchbox").incsearch().match_all({clear_matches = false})<CR>', defo)
```
It doesn't highlight until I press `n` to jump to the next result. It also shows
an error when executing the binding:
```
E5108: Error executing lua [string ":lua"]:1: attempt to index a nil value
stack traceback:
        [string ":lua"]:1: in main chunk
```

**Comment by zim0369** [comment]
Okay this keybinding works fine:
```
map("n", "<C-f>", '<cmd>lua require("searchbox").incsearch()<CR>', defo)
```
but no live highlighting of matches until I press return and then `n` to go to
the next match.

**Comment by VonHeikemen** [comment]
Maybe is a theme issue? If the highlight function fails you would get a long error message.

Try adding this in your config, right before you declare your colorscheme.

```
autocmd ColorScheme * highlight link SearchBoxMatch Search
```

**Comment by zim0369** [comment]
> ```
> autocmd ColorScheme * highlight link SearchBoxMatch Search
> ```

That worked but I want highlighting to remain.

I'm using this command rn:
`map("n", "<C-f>", ":SearchBoxIncSearch<CR>", defo)`

BTW, tried multiple themes but didn't seem to be a theme issue.

**Comment by VonHeikemen** [comment]
The type of search you want is `match_all`. incsearch ignores `clear_matches`, because it only highlights the nearest match.

You were right, the cursor did not move when using `match_all`. This feature was added now in [2169e72](https://github.com/VonHeikemen/searchbox.nvim/commit/2169e725b9c9d2d4fb0a8959654115ab6d89cbf9).

This should work now.

```lua
map("n", "<C-f>", ":SearchBoxMatchAll<CR>", { noremap = true, silent = true })
```

**Comment by zim0369** [comment]
> The type of search you want is `match_all`. incsearch ignores `clear_matches`, because it only highlights the nearest match.
> 
> You were right, the cursor did not move when using `match_all`. This feature was added now in [2169e72](https://github.com/VonHeikemen/searchbox.nvim/commit/2169e725b9c9d2d4fb0a8959654115ab6d89cbf9).
> 
> This should work now.
> 
> ```lua
> map("n", "<C-f>", ":SearchBoxMatchAll<CR>", { noremap = true, silent = true })
> ```

This is the suitable command but it doesn't jump to the nearest match.

**Comment by zim0369** [comment]
> The type of search you want is `match_all`. incsearch ignores `clear_matches`, because it only highlights the nearest match.
> 
> You were right, the cursor did not move when using `match_all`. This feature was added now in [2169e72](https://github.com/VonHeikemen/searchbox.nvim/commit/2169e725b9c9d2d4fb0a8959654115ab6d89cbf9).
> 
> This should work now.
> 
> ```lua
> map("n", "<C-f>", ":SearchBoxMatchAll<CR>", { noremap = true, silent = true })
> ```

Works like a charm!
