### ISSUE TITLE
nohl doesn't work

### ISSUE THREAD

**Issue by zim0369** [VonHeikemen/searchbox.nvim#16]
Why is `nohl` unable to clear the searchbox highlights? Is it intended?

Current situation is:
`map("n", "<C-l>", ":nohl<CR>:SearchBoxClear<CR><C-l>", { noremap = true, silent = true })`

**Comment by VonHeikemen** [comment]
I'm using a custom highlight function. `nohl` can't clear that highlight group. 

`SearchBoxClear` removes the custom highlight and then calls `nohlsearch`. Try using just `SearchBoxClear`.
