### ISSUE TITLE
Searchbox error

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [VonHeikemen/searchbox.nvim#17]
Error when executing `Searchbox commands`. Maybe this is because [nui.nvim](https://github.com/MunifTanjim/nui.nvim) latest commit (I'm not sure).

![searchbox](https://user-images.githubusercontent.com/73665622/148646142-4e9535d9-17e0-4dad-ac89-f7d051803778.png)

**Comment by VonHeikemen** [comment]
Yes it was. Should be fixed now in [60b83ba](https://github.com/VonHeikemen/searchbox.nvim/commit/60b83ba0b0f13671f1b4da699fdf7ec8cf384a7c).

**Comment by GreatestOfAllTimee** [comment]
that was fast! Thanks
