### ISSUE TITLE
match-all doesn't jump to the first match on netrw

### ISSUE THREAD

**Issue by jotacosta-fb** [VonHeikemen/searchbox.nvim#20]
`vim.api.nvim_set_keymap('n', '/', '<cmd>lua require("searchbox").match_all()<CR>', { noremap = true })`

I was trying the keymap above. It works exactly as expected in normal files (jumps to the first match after pressing enter), but in `netrw` it doesn't actually jump to the first match. Not sure if this is a feature/bug. 

Wondering if there is some option I've missed.

**Comment by jotacosta-fb** [comment]
Working now! thanks

**Comment by jotacosta-fb** [comment]
Sorry to bug again. 

If you have a split and it happens that each split as the same `netrw`, this solution jumps to the left most split. I don't think this is super relevant and I can - personally - live with it. Just fyi .

**Comment by VonHeikemen** [comment]
I'm afraid I can't fix that one. There are only two functions that allow me to set cursor position, none of them seem to work.

**Comment by jotacosta-fb** [comment]
That's ok. Your first fix works 99% of the time. I just wanted to report a small detail. No worries.
