### ISSUE TITLE
Search highlighting broken in visual mode for first character/word in selected text

### ISSUE THREAD

**Issue by Akianonymus** [VonHeikemen/searchbox.nvim#21]
Mapping: `vnoremap <leader>s <Esc><cmd>SearchBoxReplace confirm=menu visual_mode=true<CR>`

Selected text:
---

![Screenshot_20220203-231842](https://user-images.githubusercontent.com/32216346/152401328-aedaf6a0-340c-4181-a7fc-e6f06ade83e7.png)

---
First character searched:
---

![Screenshot_20220203-232016](https://user-images.githubusercontent.com/32216346/152401504-fae1fb93-4a7e-4980-97f7-2762c08e692c.png)

( first 'l' is ignored. )

---
First word searched:
---

![Screenshot_20220203-231904](https://user-images.githubusercontent.com/32216346/152401917-24cc9b09-033b-47d5-9a60-8a7b02f7578f.png)

( first 'local' is ignored. )

---
First word searched except first character:
---

![Screenshot_20220203-231946](https://user-images.githubusercontent.com/32216346/152401756-37774b91-564f-419e-99c3-c2cc68db99a7.png)

( works as intended )
---

Although it doesn't highlight the first character/word when searched, replacement does work.

**Comment by VonHeikemen** [comment]
Off by one errors...

It should be fixed now in [91808ad](https://github.com/VonHeikemen/searchbox.nvim/commit/91808add0a0db8fe014d436570b289a43fdea833). And hopefully I didn't break anything else.
