### ISSUE TITLE
SearchBoxMatchAll triggers `undo`

### ISSUE THREAD

**Issue by romgrk** [VonHeikemen/searchbox.nvim#25]
Steps:
 - Open a buffer, do some modifications
 - `:SearchBoxMatchAll`, input a query then press `<CR>`

Result:
An `undo` has been made on the buffer.

**Comment by romgrk** [comment]
The issue also appears with `SearchBoxSImple`, but not with `SearchBoxReplace`.

**Comment by VonHeikemen** [comment]
Can't reproduce the bug.

**Comment by romgrk** [comment]
Can reproduce with `nui.nvim` only, I'll transfer the bug there.
