### ISSUE TITLE
Cursor position outside buffer (search-types.lua:189)

### ISSUE THREAD

**Issue by beauwilliams** [VonHeikemen/searchbox.nvim#28]
Using this command `:SearchBoxReplace confirm=menu visual_mode=true`

Any clue what issue might be?

**Comment by beauwilliams** [comment]
Okay this works. Odd (added : at end by mistake, but it fixed the problem)

`:SearchBoxReplace confirm=menu visual_mode=true:`

**Comment by VonHeikemen** [comment]
As far as I can tell this happens when the function that gives the range of the selected returns an invalid value. It should only happen when there is no record of any selected text. I've added a validation for this, now it should show an error message, and prevent the input from showing up.

**Comment by beauwilliams** [comment]
Ah I see, all good then thanks for fixing that up :)
