### ISSUE TITLE
Live changes doesn't work after setting inccommand=nosplit

### ISSUE THREAD

**Issue by ShivamJoker** [VonHeikemen/searchbox.nvim#3]
It would be great to have an option to get the live replace feature to work with this plugin
Thanks

**Comment by VonHeikemen** [comment]
`inccommand=nosplit` only works on `command-line-mode`. When you type in the search input it's just plain `insert mode`.

Let me see what I can do.

**Comment by VonHeikemen** [comment]
Looks like this is not possible. Neovim doesn't let me modify the current buffer while the user is typing.

**Comment by ShivamJoker** [comment]
No worries thanks for trying
