### ISSUE TITLE
Wrong postion confirm menu pop in replace mode

### ISSUE THREAD

**Issue by hungnguyen1503** [VonHeikemen/searchbox.nvim#31]
Hi, I'd like to replace a word with replace confirm mode, but the popup menu is in the wrong position, I can't see a word to replace.
Could you please support me to fix it?
![image](https://user-images.githubusercontent.com/58872428/199039208-294e6cad-4630-4cf4-b291-d56039115c3b.png)
![image](https://user-images.githubusercontent.com/58872428/199039473-d86ec333-4367-4951-a08e-f10186b9f40f.png)

Here is my configuration for the plugin:
local status_ok, searchbox = pcall(require, "searchbox")
if not status_ok then
	return
end

searchbox.setup({
  defaults = {
    reverse = false,
    exact = false,
    prompt = ' ',
    modifier = 'disabled',
    confirm = 'on',
    clear_matches = true,
    show_matches = false,
  },
  popup = {
    relative = 'cursor',
    position = {
      row = 2,
      col = 0,
    },

    size = 30,
    border = {
      style = 'rounded',
      text = {
        top = ' Search ',
        top_align = 'center',
      },
    },
    win_options = {
      winhighlight = 'Normal:Normal,FloatBorder:Normal',
    },
  },
  hooks = {
    before_mount = function(input)
      -- code
    end,
    after_mount = function(input)
      -- code
    end,
    on_done = function(value, search_type)
      -- code
    end
  }
})

**Comment by VonHeikemen** [comment]
This should be fixed now in [0342b0b](https://github.com/VonHeikemen/searchbox.nvim/commit/0342b0be19ed4ab10c8a1cf53f6591117ed8692b). Please update `searchbox.nvim` and let me know if the fix works for you.

**Comment by hungnguyen1503** [comment]
The plugin has worked very well !!
Thank you for your support.
