### ISSUE TITLE
after_mount hook not working in normal mode

### ISSUE THREAD

**Issue by Davidca089** [VonHeikemen/searchbox.nvim#32]
Hello there!
After using this plugin for a while I can say im pretty happy with it! Thank you for your amazing work!

Nevertheless I am having an issue and I was wondering if you could help me out.

The thing is I am trying to add normal mode support in the replace box.
So I set up the hooks as indicated in the README.

The problem is that I am then able to enter normal mode when I hit ESC on the first window but not on the second. When I try to enter ESC to try and go from insert mode to normal mode it closes the searchbox completely. 

### Config
         return {
	"VonHeikemen/searchbox.nvim",
	dependencies = {
		"MunifTanjim/nui.nvim",
	},
	config = function()
		-- enable vim mode
		require("searchbox").setup({
			hooks = {
				after_mount = function(input)
					local opts = { buffer = input.bufnr }
					-- Esc goes to normal mode
					vim.keymap.set("i", "<Esc>", "<cmd>stopinsert<cr>", opts)
					vim.keymap.set("i", "<C-c>", "<cmd>stopinsert<cr>", opts)
				end,
			},
		})

		-- replace
		vim.keymap.set("n", "<leader>r", ":SearchBoxReplace exact=true -- <C-r>=expand('<cword>')<CR><CR>")
		vim.keymap.set("x", "<leader>r", ":SearchBoxReplace modifier=':\\C' visual_mode=true<CR>")
	end,
}

I appreciate any help you can provide! :)

**Comment by VonHeikemen** [comment]
That's bug. It should fixed now. Update the plugin and test it.
