### ISSUE TITLE
Add highlight on current search term

### ISSUE THREAD

**Issue by Pawel-Parma** [VonHeikemen/searchbox.nvim#36]
Currently there is no visual indicator showing which search term is selected.
I am expecting something like this:

![image](https://github.com/user-attachments/assets/b07e8bb2-089d-4c1f-a03b-2d5cd054a4d2)

I tried to do that myself as I saw Issue #26
I merged the commit [feat: add SearchBoxMatchCurrent](https://github.com/VonHeikemen/searchbox.nvim/pull/26/commits/d4b17c905f1bb709e38e074c991f981d611ecb16) by @romgrk to current main, but it doesn't work fully as when changing current match, as you can see in the same image I am currently on match 2 or 3 but the highlight is on match 7.

If you don't have time right now, you can guide me on where to look on the code base (for changing the current match) so I can try to add it myself.

**Comment by VonHeikemen** [comment]
I've implemented this in [c255af5](https://github.com/VonHeikemen/searchbox.nvim/commit/c255af511687ab830c8b9d3e7f19aa91bb2f2a1d). Update the plugin and let me know if it works.

**Comment by Pawel-Parma** [comment]
I found something interesting that might help you. 
When I open nvim for the first time the search works as intended, but then when I do the search for the second time the search works as shown previously

https://github.com/user-attachments/assets/c5e84574-597a-43c0-b43e-aa7d9e1ffaba

**Comment by VonHeikemen** [comment]
Are you using `<Tab>` to navigate or the default `control + l`?

**Comment by Pawel-Parma** [comment]
Yes, now everything works. Thank you.

I only have one question left as I am new to nvim. 
Why doesn't the <C-l> or <C-g> mapping work? 
I don't need a full answer if it is long, a link to wiki or article will be enough.

**Comment by VonHeikemen** [comment]
`nvim_input()` is a non-blocking function that puts your key in a queue. My guess is that makes the order of execution unpredictable, specially if you press it very quickly. Executing the `<Plug>` keymap is a blocking process, things start happening right away.
