### ISSUE TITLE
Default_value +  confirm='menu' error

### ISSUE THREAD

**Issue by JoseConseco** [VonHeikemen/searchbox.nvim#4]
After using this comand:
``` :lua require('searchbox').replace({default_value = vim.fn.expand('<cword>'), confirm = 'menu'})<CR> ```

On text  (cursor is over  'numpy' :
```python
if True:
    numpy as np
numpy as np
numpy as np 
```

Popup menu is displayed, confirm menu is displayed ok too, but then accepting first change with <ret>  gives error:
![image](https://user-images.githubusercontent.com/13521338/144662940-f5eb97dc-9f5e-4020-b11d-b50acfa1f4aa.png)

It seems error is happening only when first `numpy` is indented once, and then next occurance of `numpy` is not indented.

Btw. small feature request - can replace happen from place where cursor is located, and not from to of file?  Great plugin btw.

**Comment by VonHeikemen** [comment]
Should be fix now in [a7f20cd](https://github.com/VonHeikemen/searchbox.nvim/commit/a7f20cd18e734b696cfdb2b137af997caa3ddaba).

**Comment by JoseConseco** [comment]
Thanks @VonHeikemen  the issue is fixed .  Any chances, for searchbox.nvim to start replacing words from current cursor position, rather than from start of file?

**Comment by VonHeikemen** [comment]
>  the issue is fixed 

Awesome.

>  Any chances, for searchbox.nvim to start replacing words from current cursor position, rather than from start of file?

It is possible, just annoying to do. Open a new issue, so I can remember to look at it in another moment.
