### ISSUE TITLE
Feature: start replacing from current cursor pos

### ISSUE THREAD

**Issue by JoseConseco** [VonHeikemen/searchbox.nvim#6]
Any chances, for searchbox.nvim to start replacing words from current cursor position, rather than from start of file?
It would make it feel more like in 'standard'  editors.

**Comment by VonHeikemen** [comment]
There was an issue that prevented me from doing this. Looks like I fixed it, don't remember when, but it's gone now.

Anyway, as of [97979ab](https://github.com/VonHeikemen/searchbox.nvim/commit/97979abd4cfe6d16846e92f7a087af050f3e9c97) confirm menu will start from the cursor position in normal mode. Visual mode will still start from the beginning of the range.

**Comment by JoseConseco** [comment]
Thanks it works great now. nvim feels bit like vs code now  :) .   Btw there is small issue if you replace `string` with `string_new` then searchbox is just keep replacing current line forever:

https://user-images.githubusercontent.com/13521338/144755147-c9c068f5-a6b4-48a0-a84e-b2d5717351dc.mp4

**Comment by VonHeikemen** [comment]
Should be fixed now ([c3f2adf](https://github.com/VonHeikemen/searchbox.nvim/commit/c3f2adf4c031e0acdf37e558d7bf507188c3758e)).

---

> nvim feels bit like vs code now 

Some people might find this offensive.

**Comment by JoseConseco** [comment]
Thanks. It works great now. closing this
