### ISSUE TITLE
Working alongside gruvbox/vimade

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [VonHeikemen/searchbox.nvim#7]
Not really an issue so feel free to close, just wanted to document some troubleshooting steps I had in case anyone finds useful:

- Playing along with themes
[Some themes](https://github.com/morhetz/gruvbox/wiki/Installation) suggest using `autocmd vimenter * ++nested colorscheme theme` in your .vimrc, I found this broke the search highlighting of this plugin, so swapped back to `colorscheme theme`

- Playing along with [Vimade](https://github.com/TaDaa/vimade)
Vimade fades the background of the not active window, but I found this made the highlights not standout enough - I tried using the hook functionality to enable/disable, but I would need a "end of replace" hook. In the end I settled for a hacky solution, re-enabling Vimade 25 seconds after calling searchbox:
```vim
nnoremap <leader>/ :VimadeDisable<CR>
	\ <cmd>lua vim.defer_fn(function () vim.api.nvim_command('VimadeEnable') end, 25000)<CR>
	\ <cmd>lua require('searchbox').replace({})<CR>
```

**Comment by VonHeikemen** [comment]
I use a custom highlight group `SearchBoxMatch`, is linked to `Search`. Is not documented because I didn't think it was necessary to overwrite. You could change it after loading `searchbox`.

```vim
highlight SearchBoxMatch guibg=#SOMETHING guifg=#SOMETHING
```

About that "end replace" hook, I could make that happen. But now question is, when the `confirm` option is enabled, should it trigger after the last confirm or immediately after the second input is closed?

**Comment by BrunoGomesCoelho** [comment]
Nice, thanks for the suggestion;

For my specific case, I'd want it after the last confirm, since I have to disable the "fading" effect only when I'm done with all substitutions

**Comment by VonHeikemen** [comment]
Okay, on [0f6633c](https://github.com/VonHeikemen/searchbox.nvim/commit/0f6633c285af1092812d26ce71303b08186609c6) I added another hook, `on_done`.

```lua
require('searchbox').setup({
  hooks = {
    on_done = function(value, search_type)
      -- code
    end
  }
})
```

> on_done: It's executed after the search is finished. In the case of a successful search it gets the value submitted and the type of search as arguments. When doing a search and replace, it gets executed after the last substitution takes place. In case the search was cancelled, the first argument is `nil` and the second argument is the type of search.

Hopefully that covers your use case (and some others).
