### ISSUE TITLE
Visual mode (seach & Replace) won't work

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [VonHeikemen/searchbox.nvim#8]
Honestly I'm not quite sure how visual search work, but it seems like (visual search) not work properly.

### 1st command for (Visual Search).
> \<leader>\<leader>s 
### 2nd command for (Visual Replace).
> \<leader>\<leader>r

https://user-images.githubusercontent.com/73665622/144761673-93e6b119-6f04-4445-aed8-9060a206e2ba.mp4

**Comment by VonHeikemen** [comment]
The way "visual mode" works is by limiting the range of the search. So if you select lines 41 until 44, and look for the word `leader`, this plugin will only look in those lines. If a match is found the cursor will be placed in the first match, and when you press `n` neovim will cycle throught the matches within the lines 41 until 44. When the search fails, it prints the standard error message of a failed search (the same thing `/` does).

The behavior I'm trying to simulate is (almost) the same as this command  `:'<,'>s/leader/whatever/g`.

Can you tell what is the behaviour you expect?

**Comment by GreatestOfAllTimee** [comment]
Shame on me. what I thought was, Visual words : `viw` and replace. After that Searchbox will find and replace all the matching words too. Thank you for fast reply!
